// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent {
  router: Router;

  public editoras = new Array<Editora>;
  public livro: Livro;
  public autoresForm: string;

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(router: Router, servEditora: ControleEditoraService, servLivros: ControleLivrosService) {
    this.router = router;
    this.servEditora = servEditora;
    this.servLivros = servLivros;

    this.livro = new Livro("", 1, "", "", []);
    this.autoresForm = "";
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  };

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl("/lista");
    });
  }
}

<main class="p-4">
    <form (submit)="incluir()">
        <div class="row gx-0 pb-2">
            <h1>Dados do Livro</h1>
        </div>

        <div class="row gx-0 pb-2">
            <label for="titulo">Titulo</label>
            <input name="titulo" type="text" [(ngModel)]="livro.titulo" class="form-control" required />
        </div>

        <div class="row gx-0 pb-2">
            <label for="resumo">Resumo</label>
            <textarea name="resumo" [(ngModel)]="livro.resumo" class="form-control"></textarea>
        </div>

        <div class="row gx-0 pb-2">
            <label for="editora">Editora</label>
            <select name="editora" class="form-control" [(ngModel)]="livro.codEditora">
                <option *ngFor="let editora of editoras" [ngValue]="editora.codEditora"> {{editora.nome}}</option>
            </select>
        </div>

        <div class="row gx-0">
            <label for="autores">Autores (1 por linha)</label>
            <textarea name="autores" [(ngModel)]="autoresForm" class="form-control"></textarea>
        </div>
        <br>

        <div class="row gx-0">
            <div class="col">
                <input class="btn btn-primary" type="submit" />
            </div>
        </div>
    </form>
</main>

// clientes/livros-react/src/LivroDados.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ControleEditora } from "./controle/ControleEditora";
import { ControleLivro } from "./controle/ControleLivro";
import { Livro } from "./modelo/Livro";

function LivroDados() {
    const controleLivro = new ControleLivro();
    const controleEditora = new ControleEditora();

    let opcoes = controleEditora.getEditoras().map(x => { return { value: x.codEditora, name: x.nome } });

    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0]);

    const navigate = useNavigate();

    const tratarCombo = (evento: any): any => {
        let codEditora = parseInt(evento.target.value)
        setCodEditora(opcoes.filter(x => x.value === codEditora)[0]);
    }

    const incluir = (evento: any): void => {
        evento.preventDefault();
        let livro = new Livro("", codEditora.value, titulo, resumo, autores.split('\n'));
        controleLivro.incluir(livro).then(() => {
            navigate("/");
        });
    }

    return (
        <main>
            <form onSubmit={incluir}>
                <div className="row gx-0 pb-2">
                    <h1>Dados do Livro</h1>
                </div>

                <div className="row gx-0 pb-2">
                    <label>Titulo</label>
                    <input className="form-control" value={titulo} onChange={e => setTitulo(e.target.value)}></input>
                </div>

                <div className="row gx-0 pb-2">
                    <label>Resumo</label>
                    <textarea className="form-control" value={resumo} onChange={e => setResumo(e.target.value)}></textarea>
                </div>

                <div className="row gx-0 pb-2">
                    <label>Editora</label>
                    <select className="form-control" onChange={tratarCombo}>
                        {opcoes.map(x => { return <option key={x.value} value={x.value}>{x.name}</option> })}
                    </select>
                </div>

                <div className="row gx-0">
                    <label>Autores</label>
                    <textarea className="form-control" value={autores} onChange={e => setAutores(e.target.value)}></textarea>
                </div>
                <br></br>

                <div className="row gx-0">
                    <div className="col">
                        <input className={"btn btn-primary"} type={"submit"} value={"Salvar Dados"}></input>
                    </div>
                </div>
            </form>
        </main>
    );
}

export default LivroDados;
