// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent {
  public editoras = new Array<Editora>;
  public livros = new Array<Livro>;

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((result) => {
      this.livros = result;
    });
  };

  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((result) => {
        this.livros = result;
      });
    });
  }

  obterNome = (codigo: number): string => this.servEditora.getNomeEditora(codigo);
}

<main class="p-4" >
    <h1>Catálogo de Livros</h1>
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody *ngFor="let livro of livros">
            <tr>
                <td>
                    {{livro.titulo}}<br />
                    <button class="btn btn-danger" (click)="excluir(livro._id!)">Excluir</button>
                </td>
                <td>{{livro.resumo}}</td>
                <td>{{obterNome(livro.codEditora)}}</td>
                <td>
                    <ul *ngFor="let autor of livro.autores">
                        <li>{{autor}}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.tsx
import { useEffect, useState } from "react";
import { ControleEditora } from "./controle/ControleEditora";
import { ControleLivro } from "./controle/ControleLivro";
import { Livro } from "./modelo/Livro";


function LivroLista() {
    const controleLivro = new ControleLivro();
    const controleEditora = new ControleEditora();

    const [livros, setLivros] = useState(new Array<Livro>());
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        if (carregado)
            return;

        controleLivro.obterLivros().then((result) => {
            setCarregado(true);
            setLivros(result);
        });
    }, [carregado]);

    const excluir = (codLivro: string): any => {
        controleLivro.excluir(codLivro).then(() => {
            setCarregado(false);
        });
    }

    function LinhaLivro(props: Livro, excluir: any) {
        let nomeEditora = controleEditora.getEditora(props.codEditora);
        let autores = props.autores.map((x, i) => <li key={i}>{x}</li>);
        return <tr>
            <td>{props.titulo} <br /><button className="btn btn-danger" onClick={() => { excluir() }}>Excluir</button></td>
            <td>{props.resumo}</td>
            <td>{nomeEditora}</td>
            <td><ul>{autores}</ul></td>
        </tr>;
    }

    return (
        <main>
            <h1>Catálogo de Livros</h1>
            <table className="table">
                <thead className="table-dark">
                    <tr>
                        <th>Título</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {carregado && livros.map(x => LinhaLivro(x, () => { excluir(x._id!) }))}
                </tbody>
            </table>
        </main>
    );
}

export default LivroLista;
