// clientes/livros-next/pages/LivroLista.tsx
import { Livro } from "@/classes/modelo/Livro";
import { NextPage } from "next"
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from '../styles/Home.module.css'
import { Menu } from "../componentes/Menu";
import { LinhaLivro } from "@/componentes/LinhaLivro";
import { ControleLivro } from "@/classes/controle/ControleLivro";

const LivroLista: NextPage = () => {
    const controleLivro = new ControleLivro();
    const [livros, setLivros] = useState(new Array<Livro>());
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        controleLivro.obterLivros().then(result => {
            setLivros(result)
            setCarregado(true);
        })
    }, [carregado]);

    const excluir = (codigo: string) => {
        controleLivro.excluir(codigo).then(result => {
            setCarregado(false);
        })
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu></Menu>
            <main>
                <h1>Catálogo de Livros</h1>
                <table className="table">
                    <thead className="table-dark">
                        <tr>
                            <th>Título</th>
                            <th>Resumo</th>
                            <th>Editora</th>
                            <th>Autores</th>
                        </tr>
                    </thead>
                    <tbody>
                        {carregado && livros.map(x => LinhaLivro(x, () => { excluir(x._id) }))}
                    </tbody>
                </table>
            </main>
        </div>)
}

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent {
  public editoras = new Array<Editora>;
  public livros = new Array<Livro>;

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((result) => {
      this.livros = result;
    });
  };

  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((result) => {
        this.livros = result;
      });
    });
  }

  obterNome = (codigo: number): string => this.servEditora.getNomeEditora(codigo);
}

<main class="p-4" >
    <h1>Catálogo de Livros</h1>
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody *ngFor="let livro of livros">
            <tr>
                <td>
                    {{livro.titulo}}<br />
                    <button class="btn btn-danger" (click)="excluir(livro._id!)">Excluir</button>
                </td>
                <td>{{livro.resumo}}</td>
                <td>{{obterNome(livro.codEditora)}}</td>
                <td>
                    <ul *ngFor="let autor of livro.autores">
                        <li>{{autor}}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>
